import type { GetServerSideProps, NextPage } from "next";
import { sanityClient, urlFor } from "../sanity";
import Head from "next/head";
import { Collection } from "../typings";
import CollectionItem from "../components/CollectionItem";

interface Props {
  collections: Collection[];
}

const Home = ({ collections }: Props) => {
  return (
    <div className="max-w-7xl mx-auto flex-col min-h-screen py-20 px-10 2xl:px-0">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="mb-10 text-4xl font-extralight">
        The{" "}
        <span className="font-extrabold underline decoration-pink-600/50">
          PIGYOYO
        </span>{" "}
        NFT MARKETPLACE
      </h1>

      <main className="bg-slate-100 p-10 shadow-xl shadow-rose-400/20">
        <div className="grid space-x-3 md:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4">
          {collections.map((collection) => (
            <CollectionItem collection={collection} key={collection._id} />
          ))}
        </div>
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const query = `*[_type == "collection"]{
    _id,
    title,
    address,
    description,
    nftCollection,
    mainImage {
       asset
    },
    circleImage{
      asset
    },
    previewImage{
      asset
    },
    slug{
      current
    },
    creator-> {
      _id,
      name,
      address,
      slug{
      current
     },
  },

   
}`;

  const collections = await sanityClient.fetch(query);

  return {
    props: {
      collections,
    },
  };
};
